api_platform:
    enable_entrypoint: false
    formats:
        json:
            mime_types:
                - application/json
        html:
            mime_types:
                - text/html
    patch_formats:
        json:
            mime_types:
                - application/json
                - application/merge-patch+json
    error_formats:
        jsonproblem:
            mime_types:
                - application/problem+json
    oauth:
        pkce: true
        clientId: '%env(OAUTH_CLIENT_ID)%'
