jose:
    jku_factory:
        enabled: true
        client: 'Psr\Http\Client\ClientInterface'
        request_factory: 'Psr\Http\Message\RequestFactoryInterface'
    checkers:
        claims:
            access_token:
                claims: ['exp', 'iat', 'access_token_audience', 'access_token_issuer']
        headers:
            access_token:
                headers: ['access_token_signature_algorithm']
    jws:
        verifiers:
            access_token:
                signature_algorithms: ['RS256']
