version: '3'
rpc:
    listen: 'tcp://127.0.0.1:6001'
server:
    command: 'php -f public/index.php'
    relay: pipes
    env:
      - APP_RUNTIME: 'App\Runtime\RoadRunnerSymfonyNyholm\Runtime'
      - APP_ENV: 'prod'
http:
    address: '0.0.0.0:8080'
    middleware:
        - gzip
        - static
    static:
        dir: public
        forbid:
            - .php
            - .htaccess
    pool:
        num_workers: 32
        supervisor:
            max_worker_memory: 256
jobs:
    pool:
        num_workers: 2
        max_worker_memory: 100
    consume: []
kv:
    local:
        driver: memory
        config:
            interval: 60
metrics:
    address: '127.0.0.1:2112'
logs:
    mode: production
    encoding: console
    level: warn
