services:
  php:
    build:
      context: .
      target: frankenphp_prod
    image: ${IMAGES_PREFIX:-}app-php
    restart: unless-stopped
    env_file:
      - path: ./.env
        required: true # default
      - path: ./.env.local
        required: false
    environment:
      SERVER_NAME: ${SERVER_NAME:-localhost}, php:80
    volumes:
      - caddy_data:/data
      - caddy_config:/config

###> doctrine/doctrine-bundle ###
###< doctrine/doctrine-bundle ###

volumes:
  caddy_data:
  caddy_config:

###> doctrine/doctrine-bundle ###
###< doctrine/doctrine-bundle ###
