volumes:
  postgres16-data:

services:
  web:
    image: ghcr.io/bohanyang/bing-homepage:main
    labels:
      com.caddyserver.http.enable: true
      com.caddyserver.http.upstream.port: 80
      com.caddyserver.http.matchers.host: wp.bohan.co
