admin:
  disabled: true

apps:
  http:
    servers:
      srv0:
        listen:
          - :8000
        routes:
          - match:
              - path: ['/build/*']
            handle:
              - handler: file_server
                root: /app/public
                precompressed:
                  br: {}
                  gzip: {}
                precompressed_order: [br, gzip]
            terminal: true
          - match:
              - path: ['/bundles/*']
            handle:
              - handler: encode
                encodings: { gzip: {} }
              - handler: file_server
                root: /app/public
            terminal: true
          - match:
              - path:
                  - /*
            handle:
              - handler: encode
                encodings: { gzip: {} }
              - handler: reverse_proxy
                transport:
                  protocol: http
                  keep_alive:
                    enabled: true
                    max_idle_conns: 128
                upstreams:
                  - dial: "tcp/127.0.0.1:3000"
                trusted_proxies:
                  - 192.168.0.0/16
                  - 172.16.0.0/12
                  - 10.0.0.0/8
                  - 127.0.0.1/8
                  - fd00::/8
                  - "::1"
            terminal: true
