services:
  workspace:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ../..:/workspaces:cached
    env_file: ./workspace.env
    command: sleep infinity
    networks:
      - homepage-archive_default

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

volumes:
  postgres-data:

networks:
  homepage-archive_default:
    external: true
